=== gasparfanni/VFX06G_XMLGyak/XMLTaskVFX06G/2.feladat/DOMParseVFX06G/bin/hu/domparse/vfx06g/XMLSchemaVFX06G.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!--Egyszerű elemek-->

    <xs:element name="ceg" type="xs:string" />
    <xs:element name="telefonszam" type="telefonszamTipus" />
    <xs:element name="nev" type="xs:string" />
    <xs:element name="varos" type="xs:string" />
    <xs:element name="iranyitoszam" type="xs:int" />
    <xs:element name="utca" type="xs:string" />
    <xs:element name="hazszam" type="xs:int" />

    <xs:element name="fonok" type="xs:string" />
    <xs:element name="neve" type="xs:string" />
    <xs:element name="utca_hazszam" type="xs:string" />
    <xs:element name="email" type="emailTipus" />
    <xs:element name="facebook" type="xs:string" />

    <xs:element name="elsoIdopont" type="idoTipus" />
    <xs:element name="szolgaltatasok" type="szolgaltatasTipus" />

    <xs:element name="tipus" type="szolgaltatasTipus" />
    <xs:element name="ar" type="xs:int" />
    <xs:element name="idotartam" type="xs:int" />

    <xs:element name="fizetett" type="xs:int" />

    <xs:element name="datum" type="idoTipus" />


    <!--Saját típusok-->

    <xs:simpleType name="szolgaltatasTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Smink" />
            <xs:enumeration value="Fodrászat" />
            <xs:enumeration value="Manikűr" />
            <xs:enumeration value="Masszázs" />
            <xs:enumeration value="Kozmetikai kezelés" />
            <xs:enumeration value="Manikűr-pedikűr" />
            <xs:enumeration value="Arckezelés" />
            <xs:enumeration value="Hajfestés" />
            <xs:enumeration value="Szárítás és formázás" />
            <xs:enumeration value="Pedikűr" />
            <xs:enumeration value="Szempillafestés és szemöldök formázás" />
            <xs:enumeration value="Testradírozás" />
            <xs:enumeration value="Spa kezelések" />
            <xs:enumeration value="Körömdíszítés " />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telefonszamTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="(06(20|30|31|50|60|70)\d{7})"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idoTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([12]\d{3}.(0[1-9]|1[0-2]).(0[1-9]|[12]\d|3[01]))" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[\w\.]+@([\w]+\.)+[\w]{2,4}" />
        </xs:restriction>
    </xs:simpleType>

    <!--Felépítés-->

    <xs:element name="Szalonok_VFX06G">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="karbantarto_ceg" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="ceg" />
                            <xs:element name="kapcsolattarto" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="telefonszam" />
                                        <xs:element ref="nev" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element> 
                            <xs:element name="telephely" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="varos" />
                                        <xs:element ref="iranyitoszam" />
                                        <xs:element ref="utca" />
                                        <xs:element ref="hazszam" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element> 
                        </xs:sequence>
                        <xs:attribute name="ceg_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="szalon" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="fonok" />
                            <xs:element ref="neve" />
                            <xs:element name="cim" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="iranyitoszam" />
                                        <xs:element ref="varos" />
                                        <xs:element ref="utca_hazszam" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element> 
                            <xs:element name="elerhetoseg" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="telefonszam" />
                                        <xs:element ref="email" />
                                        <xs:element ref="facebook" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element> 
                        </xs:sequence>
                        <xs:attribute name="szalon_id" type="xs:int" />
                        <xs:attribute name="karbantartja" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="kedvezmeny" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="elsoIdopont" />
                            <xs:element ref="szolgaltatasok" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="kedvezmeny_id" type="xs:int" />
                        <xs:attribute name="vendeg_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="szolgaltatas" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="tipus" />
                            <xs:element ref="ar" />
                            <xs:element ref="idotartam" />
                        </xs:sequence>
                        <xs:attribute name="szolgaltatas_id" type="xs:int" />
                        <xs:attribute name="vendeg_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="vendeg" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="telefonszam" />
                            <xs:element ref="email" />
                            <xs:element ref="fizetett" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element ref="nev" />
                        </xs:sequence>
                        <xs:attribute name="vendeg_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="kert_szolgaltatas" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="datum" />
                        </xs:sequence>
                        <xs:attribute name="ksz_id" type="xs:int" />
                        <xs:attribute name="vevo_id" type="xs:int" />
                        <xs:attribute name="szolgaltatas_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="kerheto_szolgaltatas" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="szalon_id" type="xs:int" />
                        <xs:attribute name="szolgaltatas_id" type="xs:int" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <!--Kulcsok-->

        <xs:key name="karbantarto_ceg_kulcs">
            <xs:selector xpath="karbantarto_ceg" />
            <xs:field xpath="@ceg_id" />
        </xs:key>

        <xs:key name="szalon_kulcs">
            <xs:selector xpath="szalon" />
            <xs:field xpath="@szalon_id" />
        </xs:key>

        <xs:key name="kedvezmeny_kulcs">
            <xs:selector xpath="kedvezmeny" />
            <xs:field xpath="@kedvezmeny_id" />
        </xs:key>

        <xs:key name="szolgaltatas_kulcs">
            <xs:selector xpath="szolgaltatas" />
            <xs:field xpath="@szolgaltatas_id" />
        </xs:key>

        <xs:key name="vendeg_kulcs">
            <xs:selector xpath="vendeg" />
            <xs:field xpath="@vendeg_id" />
        </xs:key>

        <xs:key name="kert_szolgaltatas_kulcs">
            <xs:selector xpath="kert_szolgaltatas" />
            <xs:field xpath="@ksz_id" />
        </xs:key>

        <!--Idegen kulcsok-->

        <xs:keyref refer="karbantarto_ceg_kulcs" name="karbantarto_ceg_idegen_kulcs">
            <xs:selector xpath="szalon" />
            <xs:field xpath="@karbantartja" />
        </xs:keyref>

        <xs:keyref refer="szalon_kulcs" name="szalon_idegen_kulcs">
            <xs:selector xpath="alkalmazott" />
            <xs:field xpath="@munkaviszony_szalon" />
        </xs:keyref>

        <xs:keyref refer="vendeg_kulcs" name="vendeg_idegen_kulcs">
            <xs:selector xpath="kedvezmeny" />
            <xs:field xpath="@vendeg_id" />
        </xs:keyref>

        <xs:keyref refer="vendeg_kulcs" name="vendeg_kertszolgaltatas_idegen_kulcs">
            <xs:selector xpath="kert_szolgaltatas" />
            <xs:field xpath="@vevo_id" />
        </xs:keyref>

        <xs:keyref refer="szolgaltatas_kulcs" name="szolgaltatas_kertszolgaltatas_idegen_kulcs">
            <xs:selector xpath="kert_szolgaltatas" />
            <xs:field xpath="@szolgaltatas_id" />
        </xs:keyref>

        <xs:keyref refer="szalon_kulcs" name="szalon_kerhetoszolgaltatas_idegen_kulcs">
            <xs:selector xpath="kerheto_szolgaltatas" />
            <xs:field xpath="@szalon_id" />
        </xs:keyref>

        <xs:keyref refer="szolgaltatas_kulcs" name="szolgaltatas_kerhetoszolgaltatas_idegen_kulcs">
            <xs:selector xpath="kerheto_szolgaltatas" />
            <xs:field xpath="@szolgaltatas_id" />
        </xs:keyref>

        <!--1:1-->

        <xs:unique name="unique_szalon">
            <xs:selector xpath="szalon" />
            <xs:field xpath="@karbantartja" />
        </xs:unique>

    </xs:element>

</xs:schema>

=== gasparfanni/VFX06G_XMLGyak/XMLTaskVFX06G/2.feladat/DOMParseVFX06G/src/hu/domparse/vfx06g/XMLVFX06G2.xml
<?xml version="1.0" encoding="UTF-8"?>

<Szalonok_VFX06G xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaVFX06G.xsd">


    <!--Karbantartó cégek-->

    <karbantarto_ceg ceg_id="1">
        <ceg>Ceg 1</ceg>
        <kapcsolattarto>
            <telefonszam>06705684589</telefonszam>
            <nev>Kiss István</nev>
        </kapcsolattarto>
        <telephely>
            <varos>Miskolc</varos>
            <iranyitoszam>3515</iranyitoszam>
            <utca>Eper</utca>
            <hazszam>2</hazszam>
        </telephely>
    </karbantarto_ceg>

    <karbantarto_ceg ceg_id="2">
        <ceg>Ceg 2</ceg>
        <kapcsolattarto>
            <telefonszam>06705157589</telefonszam>
            <nev>Nagy Dóra</nev>
        </kapcsolattarto>
        <telephely>
            <varos>Debrecen</varos>
            <iranyitoszam>4030</iranyitoszam>
            <utca>Petőfi</utca>
            <hazszam>30</hazszam>
        </telephely>
    </karbantarto_ceg>

    <karbantarto_ceg ceg_id="3">
        <ceg>Ceg 3</ceg>
        <kapcsolattarto>
            <telefonszam>06205684511</telefonszam>
            <nev>Tóth Lilla</nev>
        </kapcsolattarto>
        <telephely>
            <varos>Miskolc</varos>
            <iranyitoszam>3515</iranyitoszam>
            <utca>Kossuth</utca>
            <hazszam>14</hazszam>
        </telephely>
    </karbantarto_ceg>

    <karbantarto_ceg ceg_id="4">
        <ceg>Ceg 4</ceg>
        <kapcsolattarto>
            <telefonszam>06205622222</telefonszam>
            <nev>Tóth István</nev>
        </kapcsolattarto>
        <telephely>
            <varos>Miskolc</varos>
            <iranyitoszam>3515</iranyitoszam>
            <utca>Búza tér</utca>
            <hazszam>2</hazszam>
        </telephely>
    </karbantarto_ceg>

    <!--Szalonok-->

    <szalon szalon_id="1" karbantartja="1">
        <fonok>Nagy Éliás</fonok>
        <neve>Szalon 1</neve>
        <cim>
            <iranyitoszam>3515</iranyitoszam>
            <varos>Miskolc</varos>
            <utca_hazszam>Petőfi utca 1</utca_hazszam>
        </cim>
        <elerhetoseg>
            <telefonszam>06705214787</telefonszam>
            <email>nagyelias@gmail.com</email>
            <facebook>nagyelias32</facebook>
        </elerhetoseg>
    </szalon>

    <szalon szalon_id="2" karbantartja="2">
        <fonok>Szegedi Dóra</fonok>
        <neve>Szalon 2</neve>
        <cim>
            <iranyitoszam>4020</iranyitoszam>
            <varos>Debrecen</varos>
            <utca_hazszam>Petőfi utca 38</utca_hazszam>
        </cim>
        <elerhetoseg>
            <telefonszam>06701112547</telefonszam>
            <email>szegedidora@gmail.com</email>
            <facebook>dorasz02</facebook>
        </elerhetoseg>
    </szalon>

    <szalon szalon_id="3" karbantartja="3">
        <fonok>Kovács Adrienn</fonok>
        <neve>Szalon 3</neve>
        <cim>
            <iranyitoszam>1024</iranyitoszam>
            <varos>Budapest</varos>
            <utca_hazszam>Arany János utca 15</utca_hazszam>
        </cim>
        <elerhetoseg>
            <telefonszam>06702345678</telefonszam>
            <email>kovacsadrienn@gmail.com</email>
            <facebook>szepsegvarazsszalon</facebook>
        </elerhetoseg>
    </szalon>

    <szalon szalon_id="4" karbantartja="4">
        <fonok>Szabó Péter</fonok>
        <neve>Szalon 4</neve>
        <cim>
            <iranyitoszam>4400</iranyitoszam>
            <varos>Nyíregyháza</varos>
            <utca_hazszam>Kossuth utca 10</utca_hazszam>
        </cim>
        <elerhetoseg>
            <telefonszam>06301234567</telefonszam>
            <email>szabopeter@gmail.com</email>
            <facebook>szepitokucko.nyiregyhaza</facebook>
        </elerhetoseg>
    </szalon>

    <!--Kedvezmény-->

    <kedvezmeny kedvezmeny_id="1" vendeg_id="1">
        <elsoIdopont>2023.04.12</elsoIdopont>
        <szolgaltatasok>Manikűr</szolgaltatasok>
        <szolgaltatasok>Smink</szolgaltatasok>
    </kedvezmeny>

    <kedvezmeny kedvezmeny_id="2" vendeg_id="1">
        <elsoIdopont>2023.07.02</elsoIdopont>
        <szolgaltatasok>Smink</szolgaltatasok>
    </kedvezmeny>

    <kedvezmeny kedvezmeny_id="3" vendeg_id="2">
        <elsoIdopont>2023.08.22</elsoIdopont>
        <szolgaltatasok>Fodrászat</szolgaltatasok>
    </kedvezmeny>

    <kedvezmeny kedvezmeny_id="4" vendeg_id="3">
        <elsoIdopont>2023.08.22</elsoIdopont>
        <szolgaltatasok>Fodrászat</szolgaltatasok>
    </kedvezmeny>

    <kedvezmeny kedvezmeny_id="5" vendeg_id="4">
        <elsoIdopont>2023.08.22</elsoIdopont>
        <szolgaltatasok>Fodrászat</szolgaltatasok>
    </kedvezmeny>

    <!--Szolgáltatások-->

    <szolgaltatas szolgaltatas_id="1" vendeg_id="1">
        <tipus>Smink</tipus>
        <ar>15000</ar>
        <idotartam>60</idotartam>
    </szolgaltatas>

    <szolgaltatas szolgaltatas_id="2" vendeg_id="3">
        <tipus>Fodrászat</tipus>
        <ar>25000</ar>
        <idotartam>90</idotartam>
    </szolgaltatas>

    <szolgaltatas szolgaltatas_id="3" vendeg_id="1">
        <tipus>Manikűr</tipus>
        <ar>8000</ar>
        <idotartam>45</idotartam>
    </szolgaltatas>

    <szolgaltatas szolgaltatas_id="4" vendeg_id="4">
        <tipus>Masszázs</tipus>
        <ar>20000</ar>
        <idotartam>75</idotartam>
    </szolgaltatas>

    <szolgaltatas szolgaltatas_id="5" vendeg_id="5">
        <tipus>Kozmetikai kezelés</tipus>
        <ar>18000</ar>
        <idotartam>60</idotartam>
    </szolgaltatas>

    <szolgaltatas szolgaltatas_id="6" vendeg_id="2">
        <tipus>Manikűr-pedikűr</tipus>
        <ar>12000</ar>
        <idotartam>90</idotartam>
    </szolgaltatas>

    <szolgaltatas szolgaltatas_id="7" vendeg_id="1">
        <tipus>Arckezelés</tipus>
        <ar>30000</ar>
        <idotartam>120</idotartam>
    </szolgaltatas>

    <szolgaltatas szolgaltatas_id="8" vendeg_id="3">
        <tipus>Hajfestés</tipus>
        <ar>18000</ar>
        <idotartam>90</idotartam>
    </szolgaltatas>

    <szolgaltatas szolgaltatas_id="9" vendeg_id="3">
        <tipus>Szárítás és formázás</tipus>
        <ar>10000</ar>
        <idotartam>45</idotartam>
    </szolgaltatas>

    <szolgaltatas szolgaltatas_id="10" vendeg_id="5">
        <tipus>Pedikűr</tipus>
        <ar>12000</ar>
        <idotartam>60</idotartam>
    </szolgaltatas>    

    <!--Vendégek-->

    <vendeg vendeg_id="1">
        <telefonszam>06301234567</telefonszam>
        <email>kovacsnora@gmail.com</email>
        <fizetett>25000</fizetett>
        <nev>Kovács Nóra</nev>
    </vendeg>

    <vendeg vendeg_id="2">
        <telefonszam>06705555555</telefonszam>
        <email>szabo.andras@gmail.com</email>
        <fizetett>18000</fizetett>
        <nev>Szabó András</nev>
    </vendeg>

    <vendeg vendeg_id="3">
        <telefonszam>06708887777</telefonszam>
        <email>molnar.rita@gmail.com</email>
        <fizetett>12000</fizetett>
        <nev>Molnár Rita</nev>
    </vendeg>

    <vendeg vendeg_id="4">
        <telefonszam>06707654321</telefonszam>
        <email>nagyferenc@gmail.com</email>
        <fizetett>30000</fizetett>
        <nev>Nagy Ferenc</nev>
    </vendeg>

    <vendeg vendeg_id="5">
        <telefonszam>06701112233</telefonszam>
        <email>kissmari@gmail.com</email>
        <fizetett>15000</fizetett>
        <nev>Kiss Mária</nev>
    </vendeg>    

    <!--Kért szolgáltatás több-több kapcsolat-->

    <kert_szolgaltatas ksz_id="1" vevo_id="2" szolgaltatas_id="3">
        <datum>2023-05-15</datum>
    </kert_szolgaltatas>

    <kert_szolgaltatas ksz_id="2" vevo_id="4" szolgaltatas_id="6">
        <datum>2023-06-02</datum>
    </kert_szolgaltatas>

    <kert_szolgaltatas ksz_id="3" vevo_id="1" szolgaltatas_id="8">
        <datum>2023-04-20</datum>
    </kert_szolgaltatas>

    <kert_szolgaltatas ksz_id="4" vevo_id="3" szolgaltatas_id="2">
        <datum>2023-05-28</datum>
    </kert_szolgaltatas>

    <kert_szolgaltatas ksz_id="5" vevo_id="5" szolgaltatas_id="10">
        <datum>2023-06-10</datum>
    </kert_szolgaltatas>

    <kert_szolgaltatas ksz_id="6" vevo_id="2" szolgaltatas_id="1">
        <datum>2023-04-15</datum>
    </kert_szolgaltatas>

    <kert_szolgaltatas ksz_id="7" vevo_id="3" szolgaltatas_id="5">
        <datum>2023-06-05</datum>
    </kert_szolgaltatas>

    <kert_szolgaltatas ksz_id="8" vevo_id="4" szolgaltatas_id="9">
        <datum>2023-05-02</datum>
    </kert_szolgaltatas>

    <!--Kérhető szolgáltatások több-több kapcsolat-->

    <kerheto_szolgaltatas szalon_id="1" szolgaltatas_id="6" />
    <kerheto_szolgaltatas szalon_id="1" szolgaltatas_id="2" />
    <kerheto_szolgaltatas szalon_id="1" szolgaltatas_id="3" />
    <kerheto_szolgaltatas szalon_id="1" szolgaltatas_id="8" />
    <kerheto_szolgaltatas szalon_id="1" szolgaltatas_id="10" />
    <kerheto_szolgaltatas szalon_id="2" szolgaltatas_id="1" />
    <kerheto_szolgaltatas szalon_id="2" szolgaltatas_id="4" />
    <kerheto_szolgaltatas szalon_id="2" szolgaltatas_id="5" />
    <kerheto_szolgaltatas szalon_id="3" szolgaltatas_id="7" />
    <kerheto_szolgaltatas szalon_id="3" szolgaltatas_id="8" />
    <kerheto_szolgaltatas szalon_id="3" szolgaltatas_id="9" />
    <kerheto_szolgaltatas szalon_id="3" szolgaltatas_id="2" />
    <kerheto_szolgaltatas szalon_id="4" szolgaltatas_id="3" />
    <kerheto_szolgaltatas szalon_id="4" szolgaltatas_id="10" />
    <kerheto_szolgaltatas szalon_id="4" szolgaltatas_id="4" />
    <kerheto_szolgaltatas szalon_id="4" szolgaltatas_id="7" />

</Szalonok_VFX06G>///C:/Users/Lenovo/eclipse-workspace/DOMParseVFX06G/src/hu/domparse/vfx06g/XMLSchemaVFX06G.xsdSzalonok_VFX06G>
